-- Treesitter
return {
    {
        'nvim-treesitter/nvim-treesitter',
        enabled = true,
        build = ':TSUpdate',
        config = function()
            require'nvim-treesitter.configs'.setup {
              highlight = {
                enable = true,              -- false will disable the whole extension
              },
              indent = {
                enable = true,
              },
              ignore_install = {},
              ensure_installed = {
                "arduino",
                "bash",
                "bibtex",
                "c",
                "cpp",
                "c_sharp",
                "clojure",
                "cmake",
                "comment",
                "commonlisp",
                "css",
                "dockerfile",
                "diff",
                "fish",
                "go",
                "graphql",
                "html",
                "java",
                "javascript",
                "jsdoc",
                "json",
                "json5",
                "julia",
                "kotlin",
                "latex",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "matlab",
                "nix",
                "pascal",
                "perl",
                "php",
                "python",
                "puppet",
                "regex",
                "rust",
                "ruby",
                "r",
                "racket",
                "scss",
                "scheme",
                "sql",
                "swift",
                "toml",
                "terraform",
                "typescript",
                "vim",
                "vue",
                "yaml",
              },
              sync_install = true,
              auto_install = true,
            }
        end
    },
    { "nvim-treesitter/nvim-treesitter-refactor" },
    { "nvim-treesitter/nvim-treesitter-textobjects" },

}
